### ISSUE TITLE
Add login/register feature

### ISSUE THREAD

**Issue by MariuszPaluch2001** [MariuszPaluch2001/diabetes-control-app#10]
### Task list for issue
- [x] Add login feature on backed
- [x] Add login feature on frontend
- [x] Add register feature on backend
- [x] Add register feature on frontend
