### ISSUE TITLE
Add better homepage

### ISSUE THREAD

**Issue by MariuszPaluch2001** [MariuszPaluch2001/diabetes-control-app#3]

**Comment by MariuszPaluch2001** [comment]
### Task list for issue:
- [ ] Add material blocks to main module
- [ ] Add blocks grid in homepage
- [ ] Add links for every block
- [ ] Center grid on page with title
- [ ] Other css customizations
